### PR TITLE
Git Repository owner of jmxtrans has changed

### PR DESCRIPTION
**Pull request by jedi4ever**
it was moved from lookfirst to jmxtrans

### CODE REVIEW

**Comment by bryanwb** [comment]
You should stop using this tool and use the collectd genericjmx plugin
instead

**Comment by jedi4ever** [comment]
@bryanwb sure - that's another option - but in some cases you don't want collect installed , jmxtrans makes that easy.
especially in java environments.

so how about a pull request approval :D

**Comment by bryanwb** [comment]
You got it, but iwont get to my laptop for a couple more hours

**Comment by bryanwb** [comment]
sorry for the delay @jedi4ever

**Pull request merged**
